on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: floms/action-caprover@v1
        with:
          host: '${{ secrets.CAPROVER_HOST }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          app: 'kvs'
          branch: master
